### ISSUE TITLE
Grid Declination Diagrams

### ISSUE THREAD

**Issue by spatialillusions** [spatialillusions/margin-info#1]
I will try to make a more general version of my code for Grid Declination Diagrams and include that as a separate function.  A demo of my existing Grid Declination Diagrams code can be found at:
http://spatialillusions.com/demos/GridDeclinationDiagrams/index.html

**Comment by roblabs** [comment]
See Notebook demo, includes

* Discussion on WMM and testing of test values
* User interface for testing Grid Declination from input of Lat, Long from World or USA maps
* User interface for testing Slope & Scale Bar
* https://observablehq.com/@roblabs/map-grids-scales-in-svg

-----

_Demo of Scale showing **cables**_

![map-grids-scales-in-svg](https://user-images.githubusercontent.com/118112/69095359-00a3b900-0a07-11ea-8cc3-62eb29ba2e19.png)
